### ISSUE TITLE
Bazaar

### ISSUE THREAD

**Issue by Angra974** [rooaaar/lang-french-extended#10]
Bonsoir.
La langue fr de base dans l'extension original fonctionne chez moi si je change 'flagrow-bazaar:'
en premirère ligne en "bazaar;"

J'ai fait la même chose pour ta transcription car elle ne fonctionne pas ( chez moi ) avec la dernière version et cela fonctionne à ce moment la correctement.

**Comment by Hiobi** [comment]
Bonjour,

J'attendais que le Yaml soit édité en conséquence avant de changer le namespace. Je suis passé à côté, merci! C'est édité, tu retrouvera les modifications dans le `dev-master` sinon tu peux patienter que je fasse une nouvelle release, dès qu'il y aura plus d'ajouts/modifications. :)

**Comment by Angra974** [comment]
Pas de souci :)
j'ai déjà fait les modifs de mon coté pour que cela fonctionne en ligne. Au moins, sur une nouvelle install, quand j'aurai tout oublié, ce sera OP :)
J'essaierai de t'aider un peu plus quand j'aurai un jour un nouveau Pc, la ce n'est que quand je tombe sur un plugin que j'utilise que je vois ce qui se passe ;)

**Comment by Hiobi** [comment]
Ça marche! Merci !
