### ISSUE TITLE
Release for beta 14

### ISSUE THREAD

**Issue by HLFH** [rooaaar/lang-french-extended#14]
Hi,

It seems this extension is not compatible with beta 14.
This is an issue to track the progress.

Thanks,
HLFH

**Comment by Hiobi** [comment]
Hi HLFH,

the extension is already compatible with beta 14,  check [dev-master](https://github.com/rooaaar/lang-french-extended#dev-master) version.
I've already update translations for beta 14, I just waiting that a majority of translated extensions, have been update to beta 14 by their developpers.Thanks !

**Comment by HLFH** [comment]
In my view when *fof/byobu* rewrite [gets released](https://github.com/FriendsOfFlarum/byobu/pull/134), it will be the time to release *lang-french-extended*.

**Comment by Hiobi** [comment]
I agree ! I'm watching releases in this purpose.

**Comment by HLFH** [comment]
@Hiobi The important *byobu* PR for beta 14 was merged. It has [been released](https://github.com/FriendsOfFlarum/byobu/releases). [Same for *fof/upload*](https://github.com/FriendsOfFlarum/upload/releases) and many other extensions. I have no more issue with beta 14 on my Flarum instance :)

**Comment by Hiobi** [comment]
Great ! I'll released it this week-end'*', thanks HLFH!

'*'**almost** this week-end...

**Comment by Hiobi** [comment]
Released ! https://github.com/rooaaar/lang-french-extended/releases/tag/v1.17.0
Thanks @HLFH ;)
