### ISSUE TITLE
Cant upgrade to flarum 1.0.2

### ISSUE THREAD

**Issue by ouraios** [rooaaar/lang-french-extended#16]
I'm getting the following error when executing `composer require rooaaar/lang-french-extended:dev-master` : 

![image](https://user-images.githubusercontent.com/9526860/120932259-5a58fa80-c6f5-11eb-8466-a344caadc7cc.png)

**Comment by Hiobi** [comment]
Hi @ouraios !

You should use dev-master branch :

```
composer require rooaaar/lang-french-extended:dev-master
php flarum cache:clear
```

The **composer.json** is compatible with 1.* on dev-master.

I planning to release a 1.* version when mainly translated extensions, will be released.

Thanks

**Comment by ouraios** [comment]
Indeed my bad, i dont have the right flarum to upgrade, this explain that ! Thanks for your quick feedback !
