### ISSUE TITLE
Byobu

### ISSUE THREAD

**Issue by Angra974** [rooaaar/lang-french-extended#6]
Salut, je pense que tu as oublié de changer la première ligne pour la traduction dans ce fichier.
A la première ligne tu as flagrow-byobu et non pas fof-byobu

cdlt.

**Comment by Angra974** [comment]
re. il te manque aussi la traduction pour 
fof-byobu.user.byobu_link => Discutions privées

**Comment by Hiobi** [comment]
> Salut, je pense que tu as oublié de changer la première ligne pour la traduction dans ce fichier.
> A la première ligne tu as flagrow-byobu et non pas fof-byobu
> 
> cdlt.

Salut,
J'avais bien fait la migration vers le nouveau namespace (dev-master) [3255099](https://github.com/rooaaar/lang-french-extended/commit/3255099cda63b05bcb5d70f29d6f11ade0c08dec#diff-f0bbd603e00dbd82070872d67a685237)
Mais je n'avais pas ajouté `fof-byobu.user.byobu_link => Discussions privées`. C'est maintenant chose faite ! Merci !
